config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'likes/new'
  root 'users#index'
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index new create show] do
      resources :comments, only: %i[new create]
      resources :likes, only: %i[create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post, public: true

    return unless user.present? # additional permissions for logged in users (they can read their own posts)

    can(:read, Post, user:)

    return unless user.admin? # additional permissions for administrators

    can :read, Post
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  validates :text, presence: true

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_save :update_like_counter

  private

  def update_like_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes
  has_many :comments

  validates :title, presence: true, length: { maximum: 250 }
  validates :author, :text, presence: true
  validates :comments_counter, :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  attribute :comments_counter, :integer, default: 0

  after_save :update_post_counter

  def five_most_recent_comment
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_post_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id

  validates :email, presence: true, uniqueness: true
  validates :name, :photo, :bio, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_most_recent_posts
    posts.order('created_at desc').limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :bio, :photo, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :bio, :photo, :email, :password, :password_confirmation, :current_password) }
  end

  def after_resetting_password_path_for(_resource)
    root_path
  end

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comments = Comment.new
  end

  def create
    @post = Post.find_by_id(params[:post_id])
    @comment = Comment.new(strong_params)
    @comment.post = @post
    @comment.author = current_user
    if @comment.save
      redirect_to user_posts_path(current_user, @post)
    else
      render :new
    end
  end

  def strong_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.author = current_user
    @like.post = Post.find(params[:post_id])
    if @like.save
      redirect_to user_post_path(@like.post.author, @like.post)
    else
      render :new
    end
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsConroller < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      # send email
      PasswordMailer.with(user: @user).reset.deliver.now
    end

    redirect_to root_path, notice: 'If an account with that email was found, we have sent a link to reset the password'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.find(params[:user_id])
    @posts = @users.posts.includes(:comments)
  end

  def show
    @post = Post.includes(:comments).find(params[:id])
    @user = User.find(params[:user_id])
    @comments = @post.five_most_recent_comment
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to user_posts_path(current_user)
    else
      render 'new'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :comments_counter, :likes_counter)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>New Comment</h1>
<section class='form-comment'>
  <%= form_with model: @comments, url: user_post_comments_path, method: :post, local: true, scope: :comment do |form| %>
    <%= form.text_area :text %>
    <%= form.submit 'Add a comment' %>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <section class="header">
  
  </section>
  <nav>
  
  </nav>
   <div class="logo">
    <h1>My RailsBlog</h1>
    <nav>
      <ul>
      <% if user_signed_in? %>
      <%= link_to 'Home', root_path %>
      <%= link_to 'Edit', edit_user_registration_path  %>
      <%= link_to 'Sign out', destroy_user_session_path, 'data-turbo-method': :delete %>
      <% elsif %>
        <%= link_to 'Sign In', new_user_session_path %>
        <%= link_to 'Sign Up', new_user_registration_path %>
    <% end %>
     </ul>
    </nav>
    <div class="main">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>

    <footer class="Footer">
      <p>&copy; 2023 || <%= Time.now.strftime('%m/%d/%Y %I:%M %p') %></p>
    </footer>
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/new.html.erb
<h1>Likes#new</h1>
<p>Find me in app/views/likes/new.html.erb</p>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head></head>
<body>

  <%# Get the user %>
  <section id='user_box'>
    <div>
      <img class='image' src=<%= @users.photo %> alt='profile picture'>
      <div class='user_name'>
        <h1 class='name'><%= @users.name %></h1>
        <p class='posts_counter'>Number of posts: <%= @users.posts_counter%></p>
      </div>
    </div>
  </section>

  <%# Get the posts of the particular user %>
  <% @posts.each do |post| %>
    <section id='post' class='post'>
      <h4><%= link_to post.title, "/users/#{@users.id}/posts/#{post.id}" %></h4>
      <div class='texts'>
        <p class='text'><%= post.text %></p>
        <div class='comlik'>
          <p>
            <span class='comments'>Comments: <%= post.comments_counter %></span>,
            <span class='likes'>Likes: <%= post.likes_counter %></span>
          </p>
        </div>
      </div>
    </section>
    <section class='comment post'>
        <p class='no_post'> <%= 'There is no comment for this post' if post.comments.length === 0 %></p>
        <% post.five_most_recent_comment.each do |comment| %>
          <p class='user_comment'><%= comment.author.name %>: <%= comment.text %></p>
        <% end %>
    </section>
  <% end %>

  <%# Pagination %>
  <div class='pagination'>
    <button>Pagination</button>
  </div>
</body>
</html>

app/views/posts/new.html.erb
<h1>I will create a new form</h1>
<h2>Add New Post</h2>
<%= form_with model: @posts, url: user_posts_path(current_user), method: :post, local: true, scope: :post do |form| %>
  <%= form.text_field :title, class: 'title', placeholder: 'Post Title' %>
  <%= form.text_area :text, class: 'text', placeholder: 'Your Post', size: "60x10" %>
  <%= form.submit 'Create', class: 'form_btn' %>
<% end %>

app/views/posts/show.html.erb
<section class='each-post'>
  <div class='post-head'>
    <h4><%= @post.title %> <span class='post-head-span'>by <%= @post.author.name %></span></h4>
    <div class='commentlike'>
      <p>
        <span class='comment'>Comments: <%= @post.comments_counter %></span>,
        <span class='like'>Likes: <%= @post.likes_counter %></span>
      </p>
    </div>
  </div>
  <div class='content'>
    <p><%= @post.text %></p>
  </div>
</section>
<section class='allcomment'>
  <% @post.comments.each do |comment| %>
    <p><%= comment.author.name %>: <%= comment.text %></p>
  <% end %>
  <div>
    <button><%= link_to 'Add New Comment', "/users/#{@user.id}/posts/#{@post.id}/comments/new" %></button>
  </div>
  <%= form_with url: "/users/#{@user.id}/posts/#{@post.author_id}/likes" do |form| %>
    <%= form.submit 'Like' %>
  <%end%>
</section>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag 'main.css' %>
</head>
<body>
  <main id='users'>
    <h1>List of all users</h1>
    <section id='user_box'>
      <% @users.each do |user| %>
        <div>
          <img class='image' src=<%= user.photo %> alt='profile picture' />
          <div class='user_name'>
            <h2 class='name'><%= link_to "#{user.name}", "/users/#{user.id}" %></h2>
            <p class='posts_counter'>Number of posts: <%= user.posts_counter%></p>
          </div>
        </div>  
      <% end %>  
    </section>
  </main>
</body>
</html>

app/views/users/show.html.erb
<section id='user_box'>
  <div>
    <img class='image' src=<%= @user.photo %> alt='profile picture' />
    <div class='user_name'>
      <h1 class='name'><%= @user.name %></h1>
      <p class='posts_counter'>Number of posts: <%= @user.posts_counter%></p>
    </div>
  </div>
  <div>
    <button><%= link_to 'Create A New Post', "/users/#{@user.id}/posts/new" %></button>
  </div>
</section>
<section class='bio'>
  <h4>Bio</h4>
  <p><%= @user.bio %></p>
</section>

<section id='posts'>
  <% @user.three_most_recent_posts.each do |recent_post| %>
    <article id='post'>
      <h4><%= recent_post.title %></h4>
      <div class='texts'>
        <p class='text'><%= recent_post.text %></p>
        <div class='comlik'>
          <p>
            <span class='comments'>Comments: <%= recent_post.comments_counter %></span>,
            <span class='likes'>Likes: <%= recent_post.likes_counter %></span>
          </p>
        </div>
      </div>
    </article>
  <% end %>
</section>

<div id='allposts'>
  <%= link_to "/users/#{@user.id}/posts" do %>
    <button>See all post</button>
  <% end %>
</div>